### ISSUE TITLE
SystemStackError when saving relation between Rails models

### ISSUE THREAD

**Issue by jabbrwcky** [triAGENS/guacamole#117]
I get a SystemStackError when trying to save a relation between two entities in Rails 4.2 using guacamole@master.

It looks like AQL oscillates between querying inbound/outbound edge for the saved models.

Code and associated log output: https://gist.github.com/jabbrwcky/b9fd9e59e6e057005f68

Is it a bug or am I missing something?

**Comment by twentyonetwice** [comment]
Try to use the current commit from git:

    gem 'guacamole', :git => 'https://github.com/triAGENS/guacamole.git'

With this version I have no problems using relations.

**Comment by jabbrwcky** [comment]
Found out that this only happens if I try to set the relation on a user that I have loaded from the database via AQL query.

This works:
```
user = User.new(...)
env = TargetEnvironment.new(...)
UsersCollection.save(user)

user.environments<<env
UsersCollection.save(user)
```

With a user object returned by AQL the resulting object is not (fully) compliant to a model, as `user<<env`causes a NoMethodError and I get the StackSystemError when trying to save the relation via the "owned" TargetEnvironment

**Comment by twentyonetwice** [comment]
You are using the version 0.4.0, which is the current available version at rubygems.org, wright? As I suggested, use the cuurent github version. In the rubygems version, it will also be impossible to update database records of related objects.

**Comment by jabbrwcky** [comment]
Think I found the reason:

```
u = User.new(...)
UsersCollection.save(u)
u.environments.respond_to? :"<<" 
 => true

u.key
 => "8054385080"

u2 = UsersCollection.by_key("8054385080")

u2.environments.respond_to? :"<<"
 => false
```

So basically it looks like you cannot add anything to the relation when you load the model from the database? :suspect:

**Comment by jabbrwcky** [comment]
````
GIT
  remote: https://github.com/triAGENS/guacamole.git
  revision: 392e3e90d7cb9dfc9bd2483f933fe03a11bc846c
  specs:
    guacamole (0.4.0)
      activemodel (>= 4.0.0)
      activesupport (>= 4.0.0)
      ashikawa-core (~> 0.14.0)
      hamster (~> 1.0.1.pre.rc.1)
      virtus (~> 1.0.1)
````

Still have the error with the latest master commit

**Comment by jabbrwcky** [comment]
Seems like the `, coerce: false` i had in the `environments` attribute definition results in the relation not being converted to a usable model but to just embed(?) the AQL query for the relation.

Removing it fixed the issue.
