### ISSUE TITLE
Errors with querying and saving relations from rails console

### ISSUE THREAD

**Issue by ashramsey** [triAGENS/guacamole#120]
I'm guessing this has not been handled yet? But I have implemented the git-recommender rails app, and am playing around with whats possible from the rails console and run into this error 

```
undefined method `model_class' for nil:NilClass
from /Users/ash/.rvm/gems/ruby-2.2.3/gems/guacamole-0.4.0/lib/guacamole/aql_query.rb:85:in `model_name'
```

when I try 

```
UsersCollection.all.first.followings.to_a
```

I've been trying to wrap my head around how to crud relations on an object using the aql syntax, but am not having much success. I set up a person class, people_collection, friendship class and seeded the people collection as per https://docs.arangodb.com/AqlExamples/CollectionQueries.html:

``` ruby
class Person
  include Guacamole::Model

  attribute :name, String
  attribute :age, Fixnum
  attribute :active, Fixnum
  attribute :gender, Fixnum

  attribute :friends, Array[Person], coerce: false
end
```

``` ruby
class PeopleCollection
  include Guacamole::Collection

  map do
    attribute :friends, via: Friendship
  end
end
```

``` ruby
class Friendship
  include Guacamole::Edge

  from :people
  to   :people
end
```

I then wanted to create a friendship between 2 people

``` ruby
p=PeopleCollection.all.first
p2=PeopleCollection.all.to_a.last
p.friends = [p2]
PeopleCollection.save p
```

and this returns:
```
Ashikawa::Core::BadSyntax: 1906: [ArangoError 1906: invalid edge between people/16161880877 and people/16163584813.]
from /Users/ash/.rvm/gems/ruby-2.2.3/gems/ashikawa-core-0.13.1/lib/ashikawa-core/error_response.rb:64:in `bad_syntax'
```

Is there something Ive missed, or do I need to use aql? when i ran the git-rcommender app, the relations/edges were saved with no error. So not sure whats going on.

Any help/pointers would be appreciated.

**Comment by ashramsey** [comment]
I realise now, I had not added the EdgeCollection classes ie the followships_collection.rb for the git-recommender app and the friendships_collection.rb

``` ruby
class FriendshipsCollection
  include Guacamole::EdgeCollection

  class << self
    def mapper_for_target(model)
      vertex_mapper.first
    end

    def mapper_for_start(model)
      vertex_mapper.first
    end
  end
end
```

So now i get a different error :-)

```
pry(main)> p=PeopleCollection.all.first ; p2=PeopleCollection.all.to_a.last ; p.friends = [p2] ; PeopleCollection.save(p)
Ashikawa::Core::ResourceNotFound: Status 404: The Resource you requested was not found on the server
from /Users/ash/.rvm/gems/ruby-2.2.3/gems/ashikawa-core-0.13.1/lib/ashikawa-core/error_response.rb:115:in `resource_not_found_in_graph_scope'
```

**Comment by mertak** [comment]
Did you created the database and collections? Go to Arango web interface, for example http://localhost:8529 . I think this will solve your problem.

**Comment by ashramsey** [comment]
yeah, i can see all my collections are there in my specified rails database, and I managed to save the collection of people, data from here: https://docs.arangodb.com/AqlExamples/CollectionQueries.html.

Eg, I am able to query the people collection:

``` ruby
PeopleCollection.all.count
```

returns 20

This would suggest the database has been created and the collection is there, right?

**Comment by ashramsey** [comment]
Oh, so I deleted and then created the database again and I was able to seed my people collection and then save a friendship from the console.

I mustve done something wrong initially.

Thanks for your help!
